# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6c34a2da08cadfadddc0d64e78a6b9f001422df751ad6acc09c746f63ece8a5ef3d7ae2abffa944e062af3e229ba5829cfa0e8010971e093ea65c7344411728f

test:
  secret_key_base: 54451973db0f5a21fcaed98c1e1f661f332327fd294da85ffdcdeea8ce0ecb47dc36694cf9dfd9f4ef6cac22ef234b62ec4196c7ab625c641b50758e7ec82a3d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
